# Generated by Django 3.2.9 on 2021-11-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0003_auto_20211124_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
