# Generated by Django 3.2.9 on 2021-11-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0004_delete_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='phono',
            field=models.IntegerField(default=0),
        ),
    ]
