# Generated by Django 3.2.9 on 2021-11-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0005_auto_20211128_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='suscription',
            field=models.BooleanField(default='null'),
        ),
    ]
