# Generated by Django 3.2.9 on 2021-11-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0007_auto_20211129_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
