# Generated by Django 3.2.9 on 2021-12-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0008_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Imagen')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de la imagen')),
            ],
        ),
    ]
