# Generated by Django 3.2.9 on 2022-12-05 07:27

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Apellido')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('city', models.TextField(max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z-ñ ]*$', 'El campo ciudad no puede contener números o caracteres especiales')], verbose_name='Ciudad')),
                ('subject', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z-ñ ]*$', 'El asunto no puede contener números o caracteres especiales')], verbose_name='Asunto')),
                ('description', models.TextField(max_length=400, verbose_name='Tu consulta')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Imagen')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de la imagen')),
            ],
        ),
    ]
