# Generated by Django 3.2.9 on 2022-01-19 15:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='Encabezado')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Margen',
                'verbose_name_plural': 'Márgenes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('description', ckeditor.fields.RichTextField(default=False, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Imagen')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL amigable')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de página')),
                ('dropdown_one', models.BooleanField(default=False, verbose_name='Menú desplegable uno')),
                ('dropdown_two', models.BooleanField(default=False, verbose_name='Menú desplegable dos')),
                ('visible', models.BooleanField(verbose_name='¿Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Imagen')),
                ('gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.gallery')),
            ],
        ),
    ]
