# Generated by Django 3.2.9 on 2022-01-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_asside_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='gallery',
            field=models.BooleanField(default=False, verbose_name='¿Galería?'),
        ),
    ]
