# Generated by Django 3.2.9 on 2021-11-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211125_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='dropdown_one',
            field=models.BooleanField(default=0, verbose_name='Menú desplegable uno'),
        ),
        migrations.AddField(
            model_name='page',
            name='dropdown_two',
            field=models.BooleanField(default=0, verbose_name='Menú desplegable dos'),
        ),
    ]
