# Generated by Django 3.2.9 on 2022-01-23 18:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='asside',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=False, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Contenido'),
        ),
    ]
