# Generated by Django 3.2.9 on 2021-12-27 05:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('description', ckeditor.fields.RichTextField(default='null', verbose_name='Descripción')),
                ('image', models.ImageField(default='null', upload_to='images', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='Imagen')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de la imagen')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null', upload_to='images', verbose_name='Imagen')),
                ('gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.gallery')),
            ],
        ),
    ]
