# Generated by Django 3.2.9 on 2021-12-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_gallery_galleryimages_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider', verbose_name='Imagen'),
        ),
    ]
