# Generated by Django 3.2.9 on 2021-12-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_slider_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
